### ISSUE TITLE
Use of `/` for Vault root

### ISSUE THREAD

**Issue by mayurankv** [tillahoffmann/obsidian-file-include#1]
Would it be possible to use `~/` or ideally something else like `=/` or `+/` to indicate vault root? I can only imagine that this may confuse users pasting absolute system paths? No worries if you disagree!

**Comment by tillahoffmann** [comment]
Good point. The reason I originally stuck with `/` is that all other characters are valid in path names on Linux; `~/` would probably lead to similar confusion with the user root. 

Having said that, naming a file `=` or `+` would seem like an odd choice. Are there other characters we could use?

**Comment by mayurankv** [comment]
Hmm I do agree. The existing paths are:
- `/` Root Dir
- `~/` Home Dir
- `./` Current Dir
- `../` Parent Dir (of Current Dir)

I agree `=/` and `+/` are weird.
Another one similar to home directory could be `≈/` but that is `alt-x` on my keyboard and definitely not convenient.
`-/` is visually very similar to home directory so I would avoid that.
Possibly `.../` which has no mapping in UNIX (as far as I am aware - though users can set aliases for shell navigation) but that also isn't very convenient.
A very easy to distinguish possibility would be `@/`, its pretty clearly not UNIX syntax.

Having said this I would probably go for something like `//`which I believe also has no UNIX meaning. Its easy to type and similar to root directory syntax which is kind of what is trying to be emulated. I would suggest this but the other options would also be better than `/` alone in my opinion.

**Comment by tillahoffmann** [comment]
Yeah `@/` seems like a good idea.

**Comment by tillahoffmann** [comment]
Thanks for the suggestion, @mayurankv!
