### ISSUE TITLE
Using incorrect sourcePath on render

### ISSUE THREAD

**Issue by mayurankv** [tillahoffmann/obsidian-file-include#3]
In the `main.ts` file, you have the line 

```
await MarkdownRenderer.renderMarkdown(markdown, el, include_path, view);
```

which uses the `include_path` parameter you use for extracting the code file. However this is the incorrect parameter to pass back, it should be the `context.sourcepath` which is returned. This means that any postMarkdownProcessor running on the codeblock gets the wrong context and does not work as intended. This can be fixed by changing `include_path` here to `context.sourcepath`.

Apologies if I'm missing something but this is causing some plugin interference for me.

**Comment by tillahoffmann** [comment]
Thanks for reporting. Should be fixed in https://github.com/tillahoffmann/obsidian-file-include/releases/tag/1.1.2.
